### ISSUE TITLE
Add "Tested With" column

### ISSUE THREAD

**Issue by ryester19** [HonkingGoose/proton_codecs_media_support_tracker#1]
Might be beneficial to have another column added so we can keep track of which proton/proton-ge/proton-tkg version was used for the entry

**Comment by HonkingGoose** [comment]
That's a good idea!

However I'm running into issues with keeping the table readable, this is not a new problem though, the old markdown tables are hard to edit as well.... :zany_face: 

I'm currently fighting against Prettier to format my Markdown tables the way I want.
If we add even more columns the tables will be even harder to read/edit.

**Comment by ryester19** [comment]
I see what you mean. Remarks is really the only column that fluctuates wildly when it comes to character count. Maybe put the Tested With column before Remarks?

**Comment by HonkingGoose** [comment]
Yeah tested with should go before remarks.
