### ISSUE TITLE
how 2 use

### ISSUE THREAD

**Issue by ewof** [HonkingGoose/proton_codecs_media_support_tracker#41]
can i use this before its pushed? if so how 2 am kinda dumb sorry

**Comment by HonkingGoose** [comment]
You can view the tables here: https://github.com/HonkingGoose/proton_codecs_media_support_tracker/tree/main/tables

If you want to add a new entry to the table, read this: https://github.com/HonkingGoose/proton_codecs_media_support_tracker#how-to-contribute

**Comment by ewof** [comment]
how do i use the tables and get my proton to play vids and stuff correctly

**Comment by HonkingGoose** [comment]
This repository does not contain any codecs or software to help you run games which don't work under Valve's official Proton software.

Make sure you read the [README.md](https://github.com/HonkingGoose/proton_codecs_media_support_tracker/blob/main/README.md).
